name = "chatcoder-light"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "chatcoder-light-prod"

[vars]
NODE_ENV = "production"
SIGNUP_TOKEN = "chatcoder2025secure"
JWT_SECRET = "chatcoder-super-secret-jwt-key-2025-secure-string"

# MongoDB Atlas 연결 설정
MONGODB_URI = "mongodb+srv://CodeNameX0:Qwerty11@cluster0.k8t2y68.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
MONGODB_DATABASE = "chatcoder"

[env.production.vars]
NODE_ENV = "production"
DOMAIN = "code-nex.store"
SIGNUP_TOKEN = "chatcoder2025production"
JWT_SECRET = "chatcoder-production-jwt-secret-2025-ultra-secure"

# Production MongoDB Atlas 연결 설정
MONGODB_URI = "mongodb+srv://CodeNameX0:Qwerty11@cluster0.k8t2y68.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
MONGODB_DATABASE = "chatcoder"