name = "chatcoder-light"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "chatcoder-light-prod"

[vars]
NODE_ENV = "production"
SIGNUP_TOKEN = "chatcoder2025secure"
JWT_SECRET = "chatcoder-super-secret-jwt-key-2025-secure-string"

# 메모리 기반 JSON 데이터베이스 (MongoDB 불필요)
DATABASE_TYPE = "memory"

[env.production.vars]
NODE_ENV = "production"
DOMAIN = "code-nex.store"
SIGNUP_TOKEN = "chatcoder2025production"
JWT_SECRET = "chatcoder-production-jwt-secret-2025-ultra-secure"

# Production 메모리 기반 JSON 데이터베이스
DATABASE_TYPE = "memory"